import { Outfit } from "next/font/google";
import "./globals.css";

const outfitFont = Outfit({ subsets: ['latin'], weight: ["400", "500", "600", "700"] });

export const metadata = {
  title: "Ruby relish",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Add the favicon here */}
        <link rel="icon" href="/logo1.png" type="image/png" />
        <title>{`Delicious Easy Dinner Recipes & Local Restaurant Guides | Your Ultimate Travel Companion`}</title>
<meta name="description" content={`Discover quick and easy recipes, explore the best local restaurants, and find unbeatable hotel deals. Your guide to a delightful culinary and travel experience awaits!`} />
  </head>
      <body className={outfitFont.className}>
        {children}
      </body>
    </html>
  );
}